### ISSUE TITLE
[FR]-REFACTOR-Move all Javascript into JS files and refactor links in all files to update

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#276] opened 2019-01-06 11:25 UTC
**Is your feature request related to a problem? Please describe.**
CODE REFACTOR

**Describe the solution you'd like**
1. Invoice Related Functions
2. Check all manage pages. 
**Describe alternatives you've considered**

**Additional context**

**Comment by suryaveer5320129** [comment] 2019-01-19 15:05
duplicate of #318

**Closed by suryaveer5320129** 2019-01-19 15:05 UTC
Labels: duplicate
